version: '3.7'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: fernando
      POSTGRES_PASSWORD: nascimento
      POSTGRES_DB: dataBase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: